
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'F5B1A26173BEB70AD20AE4AF68D4E767'
    
_lr_action_items = {'$end':([2,3,4,5,8,11,12,14,],[-4,-2,0,-7,-3,-6,-1,-5,]),'LPAREN':([0,1,2,5,6,9,10,11,14,],[1,1,1,-7,10,1,1,-6,-5,]),'PLUS':([2,3,4,5,7,8,11,12,13,14,],[-4,-2,9,-7,9,-3,-6,-1,9,-5,]),'LETTER':([0,1,2,5,9,10,11,14,],[5,5,5,-7,5,5,-6,-5,]),'GSM':([0,1,2,5,9,10,11,14,],[6,6,6,-7,6,6,-6,-5,]),'RPAREN':([2,3,5,7,8,11,12,13,14,],[-4,-2,-7,11,-3,-6,-1,14,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'term':([0,1,9,10,],[3,3,12,3,]),'expression':([0,1,10,],[4,7,13,]),'factor':([0,1,2,9,10,],[2,2,8,2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parsing.py',19),
  ('expression -> term','expression',1,'p_expression_term','parsing.py',23),
  ('term -> factor factor','term',2,'p_term_times','parsing.py',27),
  ('term -> factor','term',1,'p_term_factor','parsing.py',31),
  ('factor -> GSM LPAREN expression RPAREN','factor',4,'p_factor_gsm','parsing.py',35),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_group','parsing.py',39),
  ('factor -> LETTER','factor',1,'p_factor_letter','parsing.py',43),
]
