
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'GSM LETTER LPAREN PLUS RPARENexpression : expression PLUS termexpression : termterm : factor factorterm : factorfactor : GSM LPAREN expression RPARENfactor : LPAREN expression RPARENfactor : LETTER'
    
_lr_action_items = {'GSM':([0,3,5,6,7,9,13,14,],[4,4,4,-7,4,4,-6,-5,]),'LPAREN':([0,3,4,5,6,7,9,13,14,],[5,5,9,5,-7,5,5,-6,-5,]),'LETTER':([0,3,5,6,7,9,13,14,],[6,6,6,-7,6,6,-6,-5,]),'$end':([1,2,3,6,8,11,13,14,],[0,-2,-4,-7,-3,-1,-6,-5,]),'PLUS':([1,2,3,6,8,10,11,12,13,14,],[7,-2,-4,-7,-3,7,-1,7,-6,-5,]),'RPAREN':([2,3,6,8,10,11,12,13,14,],[-2,-4,-7,-3,13,-1,14,-6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,5,9,],[1,10,12,]),'term':([0,5,7,9,],[2,2,11,2,]),'factor':([0,3,5,7,9,],[3,8,3,3,3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parsing.py',19),
  ('expression -> term','expression',1,'p_expression_term','parsing.py',23),
  ('term -> factor factor','term',2,'p_term_times','parsing.py',27),
  ('term -> factor','term',1,'p_term_factor','parsing.py',31),
  ('factor -> GSM LPAREN expression RPAREN','factor',4,'p_factor_gsm','parsing.py',35),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_group','parsing.py',39),
  ('factor -> LETTER','factor',1,'p_factor_letter','parsing.py',43),
]
